server:
  port: 8088

spring:
  datasource:
    name: tengyin
    url: jdbc:mysql://sh-cdb-gn0zelmo.sql.tencentcdb.com:61240/db_caizhi_manage?characterEncoding=UTF-8
    username: caizhi_dev
    password: caizhiUser4Dev
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

my:
  name: hex
  age: 25