server:
  port: 8088

spring:
  datasource:
    name: tengyin
    url: jdbc:mysql://localhost:3306/hexian?serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

my:
  name: hex
  age: 25