server:
  port: 8877
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    name: test
    url: jdbc:mysql://172.28.233.26:3316/aimed_doctor?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: skyworth
    driver-class-name: com.mysql.cj.jdbc.Driver
    min-idle: 2
    initial-size: 5
    max-active: 10
    max-wait: 2000
    validation-query: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: true