server:
  port: 8877
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    name: test
    url: jdbc:mysql://172.28.233.26:3316/aimed_doctor?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: skyworth
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    database: MYSQL
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wechat:
  miniapp:
    configs:
      - appid: wx1c570017b78e796d
        secret: 35a3d3cfffd1cefdbbe7cfa94a524c41
        token: k9NJjiv0h2ylIB24c7mW3tgM
        aesKey: yOzC4z4kwmwigQ4Hj5TP1lEIU4wYmS0U6VlX8MANxyD
        msgDataFormat: JSON
infra:
  mqtt:
    domain: device
    clientId: server_dev
    qos: 1
    #    serverURIs[0]: tcp://192.168.233.71:1883
    serverURIs[0]: tcp://172.28.233.27:1883
    userName: emqx_u
    password: public
    topics:
      - skyAi/device/#